# Generated by Django 4.1.3 on 2022-11-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='img',
            field=models.ImageField(default='djhx', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
